### ISSUE TITLE
pwm output

### ISSUE THREAD

**Issue by exekutive** [piconomix/px-fwlib#2]
Neat app!

I think a cool addition would be a command that behaved like the analogwrite function in Arduino.

**Comment by pieterconradie** [comment]
Hi @exekutive,

Thanks for the suggestion :)

The Arduino Uno has 6 software PWM pins, but the frequency is quite low (490 Hz / 980 Hz) with course resolution (see [HERE](https://www.arduino.cc/reference/en/language/functions/analog-io/analogwrite/)).  Would you want exactly the same, or would you be happy with (say) one pin connection to a Hardware PWM timer with more frequency / resolution options?

Best regards,
Pieter

**Comment by exekutive** [comment]
0.5 or 1 kHz is enough for things like LED dimming. Other applications perhaps not.

One pin is also probably enough. I use the CLI for testing/troubleshooting/prototyping on the fly, which means you don't _need_ to have a lot of peripherals connected at once.

So to answer your question, either method would satisfy my needs, and in a perfect world we would have both :)
