### ISSUE TITLE
Bug in px_log_fs

### ISSUE THREAD

**Issue by celephicus** [piconomix/px-fwlib#9]
Greetings,

Basically I think I've identified a bug in px-log, when the log rolls round having filled all available sectors it erases the wrong sector, starts writing in that sector, and when it fills, logs a trace that the log is corrupt. I have verified that I am writing to the correct addresses in my memory device. I am using only 3 sectors, which is a bit small I suppose, but it makes for easier debugging. .

Target is ATMEGA2560. 

The guts of px_log_fs_cfg.h is below:
#define PX_LOG_FS_CFG_PAGE_SIZE         256 
#define PX_LOG_FS_CFG_ERASE_BLOCK_SIZE  16
#define PX_LOG_FS_CFG_REC_DATA_SIZE     6	
#define PX_LOG_FS_CFG_STOP_WR_WHEN_FULL 0

init:
		const px_log_fs_err_t rc = px_log_fs_init(&f_px_log_fs_handle, 0,  3 * PX_LOG_FS_CFG_ERASE_BLOCK_SIZE - 1);

write:	
		const px_log_fs_err_t rc = px_log_fs_wr(&f_px_log_fs_handle, rec, sizeof(driver_speed_log_record_t));

This is what happens:

log after init on an erased memory:
	Page start: 0x0000
	Page end: 0x002F
	Page size: 256
	Record size: 8
	Record data size: 6
	Records per page: 31
	First page: 65535
	Last page: 65535
	Write p: 0x0000, 0x0004
	Read p: 0x0000, 0x0000

			0      1      2      3      4      5      6      7      8      9      A      B      C      D      E      F      

	0x0000: x      x      x      x      x      x      x      x      x      x      x      x      x      x      x      x      
	0x0010: x      x      x      x      x      x      x      x      x      x      x      x      x      x      x      x      
	0x0020: x      x      x      x      x      x      x      x      x      x      x      x      x      x      x      x      

log after filling memory with records:
	Page start: 0x0000
	Page end: 0x002F
	Page size: 256
	Record size: 8
	Record data size: 6
	Records per page: 31
	First page: 0
	Last page: 47
	Write p: 0x0000, 0x0004
	Read p: 0x0000, 0x0000

			0      1      2      3      4      5      6      7      8      9      A      B      C      D      E      F      

	0x0000: U 0000 U 0001 U 0002 U 0003 U 0004 U 0005 U 0006 U 0007 U 0008 U 0009 U 000a U 000b U 000c U 000d U 000e U 000f 
	0x0010: U 0010 U 0011 U 0012 U 0013 U 0014 U 0015 U 0016 U 0017 U 0018 U 0019 U 001a U 001b U 001c U 001d U 001e U 001f 
	0x0020: U 0020 U 0021 U 0022 U 0023 U 0024 U 0025 U 0026 U 0027 U 0028 U 0029 U 002a U 002b U 002c U 002d U 002e U 002f 

log after writing one more record:
	Page start: 0x0000
	Page end: 0x002F
	Page size: 256
	Record size: 8
	Record data size: 6
	Records per page: 31
	First page: 0
	Last page: 16
	Write p: 0x0010, 0x000C
	Read p: 0x0000, 0x0000

			0      1      2      3      4      5      6      7      8      9      A      B      C      D      E      F      

	0x0000: U 0000 U 0001 U 0002 U 0003 U 0004 U 0005 U 0006 U 0007 U 0008 U 0009 U 000a U 000b U 000c U 000d U 000e U 000f 
	0x0010: U 0030 x      x      x      x      x      x      x      x      x      x      x      x      x      x      x      
	0x0020: U 0020 U 0021 U 0022 U 0023 U 0024 U 0025 U 0026 U 0027 U 0028 U 0029 U 002a U 002b U 002c U 002d U 002e U 002f 

After writing reet of sector plus ONE more record:
TRACE: 10,707: ERROR: File system must be corrupt (line no. in log-fs.c)

**Comment by pieterconradie** [comment]
Hi @celephicus,

Thanks for the feedback, I really appreciate it :) Which version are you using? The one in Release 0.9.3 or the latest version in the GitHub master branch?

FYI, I have been meaning to do a complete rewrite and move px_log_fs to it's own Github repo but I'm swamped and can't predict when I will get to it (good intentions...)

Best regards,
Pieter

**Comment by celephicus** [comment]
Hi Pieter,

Release 0.93. If you need any other info please ask as it's sitting my desk. No huge urgency as the customer hasn't placed an order yet but they will... I hope, else I'll have to cancel Christmas!

Could I ask did you test filling the log till it wraps? I'm not certain, but it looks like the problem will always occur irrespective of sector count or record size. If you did test it, what sizes did you use? These sorts of logs are complex  in that they have to deal with a lot of different cases, mainly corruption, so it could usefully be tested on a desktop with RAM standing in for Flash memory, what do you think? 

I can see how archiving could be useful if you have a use case for it. Another solution would just be to record the record index and have a method to seek to index and then carry on reading.

**Comment by pieterconradie** [comment]
Hi @celephicus,

I've made a new release today with the latest version of px_log_fs. Please try and see if that fixes your problem. I can debug this version if the bug persists.

Best regards,
Pieter

**Comment by celephicus** [comment]
Thanks so much,  I'll have a look tomorrow.
